version: '3'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8089:8089"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    entrypoint: ["/bin/sh", "/tmp/entrypoint.sh"]
